irqchip: Provide resume and suspend functions defaults
Define suspend and resume function as null when CONFIG_PM_SLEEP is unset
to avoid build failure due to

  irq-imx-irqsteer.c:386:28: error: 'imx_irqsteer_runtime_suspend' undeclared here (not in a function)

  irq-imx-irqsteer.c:387:28: error: 'imx_irqsteer_runtime_resume' undeclared here (not in a function)